### ISSUE TITLE
Open Terrain Generator (OTG) Not Enough Biome IDs Error

### ISSUE THREAD

**Issue by huesofvermillion** [DimensionalDevelopment/JustEnoughIDs#101]
https://paste.dimdev.org/koqetuviji.mccrash

Getting an error when generating a new world: 

Description: Exception in server tick loop

java.lang.RuntimeException: Biome could not be registered, no free biome id's!
    at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:484)
    at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:208)
    at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:134)
    at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:74)
    at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:362)
    at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:146)
    at net.minecraft.world.WorldProvider.init(WorldProvider.java:58)
    at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:121)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

**Comment by TerdyTheTerd** [comment]
Have you tried running this with their newer release, v8.3? Also make sure the world configs for OTG are not from a previous version, as that will make OTG use its older custom biome rather than its new virtual/dynamic biome id's.

**Comment by DukeTwoCan** [comment]
> 
> 
> Have you tried running this with their newer release, v8.3? Also make sure the world configs for OTG are not from a previous version, as that will make OTG use its older custom biome rather than its new virtual/dynamic biome id's.

How would one update these configs?

**Comment by juraj-hrivnak** [comment]
I am was also experiencing this issue. I used **Advanced Rocketry** which adds a lot of dimensions.
Removing the **Advanced Rocketry** solved the issue for me.
