### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by erwin1234777** [DimensionalDevelopment/JustEnoughIDs#127]
[18:30:04] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:30:04] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:30:04] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:30:04] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[18:30:04] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\DELL\Twitch\Minecraft\Install\runtime\jre-x64
[18:30:05] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[18:30:05] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[18:30:05] [main/INFO]: Searching C:\Users\DELL\Twitch\Minecraft\Instances\Maybe this works\mods for mods
[18:30:05] [main/INFO]: Searching C:\Users\DELL\Twitch\Minecraft\Instances\Maybe this works\mods\1.12.2 for mods
[18:30:05] [main/WARN]: The coremod org.minimallycorrect.libloader.LibLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:05] [main/WARN]: The coremod LibLoader (org.minimallycorrect.libloader.LibLoader) is not signed!
[18:30:08] [main/INFO]: Found libs:
[com.eclipsesource.minimal-json.minimal-json-0.9.4
org.javassist.javassist-3.22.0-CR1
org.minimallycorrect.modpatcher.ModPatcher-1.12-SNAPSHOT
org.minimallycorrect.mixin.Mixin-1.0-SNAPSHOT
com.github.javaparser.javaparser-core-3.2.4
org.json.json-20090211
me.nallar.whocalled.WhoCalled-1.1
me.nallar.JavaPatcher-1.8
org.minimallycorrect.javatransformer.JavaTransformer-1.8.3]
[18:30:08] [main/INFO]: Current LaunchClassLoader URLs:
[file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/google/guava/guava/21.0/guava-21.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
file:/C:/Users/DELL/Twitch/Minecraft/Install/versions/1.12.2/1.12.2.jar
file:/C:/Users/DELL/Twitch/Minecraft/Instances/Maybe%20this%20works/mods/%23%20LibLoader.jar]
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Apotheosis-1.12.2-1.12.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod ApotheosisCore (shadows.ApotheosisCore) is not signed!
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.b166.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:08] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in biggerpacketsplz-since1.8-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:08] [main/WARN]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[18:30:08] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.1.30.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:08] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:08] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[18:30:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in DefaultSettings-1.8.x-1.12.x-2.1.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod de.pt400c.defaultsettings.core.DefaultSettingsPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.0.2.jar
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod com.endertech.minecraft.forge.coremod.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod CorePlugin (com.endertech.minecraft.forge.coremod.CorePlugin) is not signed!
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HammerCore-1.12.2-2.0.6.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod com.creativemd.itemphysic.ItemPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod ItemPatchingLoader (com.creativemd.itemphysic.ItemPatchingLoader) is not signed!
[18:30:09] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from JustEnoughIDs-1.0.3-54.jar
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from levelup2-1.3.0-shaded.jar
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F4.jar
[18:30:09] [main/WARN]: The coremod OTGCorePlugin (com.pg85.otg.forge.asm.excluded.launch.OTGCorePlugin) is not signed!
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-178.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[18:30:09] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in sampler-1.73.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod sampler.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod LoadingPlugin (sampler.LoadingPlugin) is not signed!
[18:30:09] [main/INFO]: startup sampling started
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.1.5.jar
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ThaumicAugmentation-1.12.2-1.1.17.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in TickProfiler-1.12-0.0.7.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:30:09] [main/WARN]: The coremod org.minimallycorrect.tickprofiler.minecraft.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:09] [main/WARN]: The coremod CoreMod (org.minimallycorrect.tickprofiler.minecraft.CoreMod) is not signed!
[18:30:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-99.jar
[18:30:10] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:30:10] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[18:30:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:30:10] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[18:30:10] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[18:30:10] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[18:30:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more

Deleted mods one by one, started working when your mod was removed, so im pointing it as guilty

**Comment by CitrusHappy** [comment]
seconded, with two logs same crash
[crash1](https://paste.dimdev.org/yeriyozayi.mccrash)
[crash2](https://paste.dimdev.org/yumigozefa.mccrash)

**Comment by Redd56** [comment]
it seems this verrsion is very broke, mp crashes, crashes on boot
