### ISSUE TITLE
Incompatible with sponge

### ISSUE THREAD

**Issue by barcharcraz** [DimensionalDevelopment/JustEnoughIDs#33]
When loaded with spongeforge I get a crash in the sponge transformers

```
MultiMC version: 0.6.2-develop-1246


Minecraft folder is:
C:/Users/barch/Documents/MultiMC/instances/stable/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_181/bin/javaw.exe


Java is version 1.8.0_181, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/barch/Documents/MultiMC/instances/stable/natives

Libraries:
  C:/Users/barch/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/barch/Documents/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/barch/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/barch/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.4.2760/forge-1.12.2-14.23.4.2760-universal.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/barch/Documents/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/barch/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/barch/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/barch/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/barch/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  JustEnoughIDs-1.0.1-16
  spongeforge-1.12.2-2705-7.1.0-BETA-3445

Params:
  --username  --version MultiMC5 --gameDir C:/Users/barch/Documents/MultiMC/instances/stable/.minecraft --assetsDir C:/Users/barch/Documents/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:+UseG1GC, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 24732


Using onesix launcher.

[01:59:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:59:45] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[01:59:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[01:59:45] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2760 for Minecraft 1.12.2 loading
[01:59:45] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_181
[01:59:45] [main/INFO] [FML]: Searching C:\Users\barch\Documents\MultiMC\instances\stable\.minecraft\mods for mods
[01:59:45] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from JustEnoughIDs-1.0.1-16.jar
[01:59:46] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2705-7.1.0-BETA-3445.jar
[01:59:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:59:46] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[01:59:46] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/C:/Users/barch/Documents/MultiMC/instances/stable/.minecraft/mods/JustEnoughIDs-1.0.1-16.jar Service=LaunchWrapper Env=CLIENT
[01:59:46] [main/WARN] [FML]: The coremod JEIDLoadingPlugin (org.dimdev.jeid.JEIDLoadingPlugin) is not signed!
[01:59:46] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[01:59:46] [main/WARN] [mixin]: Mixin config mixins.common.api.json requires mixin subsystem version 0.7.10 but 0.7.8 was found. The mixin config will not be applied.
[01:59:46] [main/ERROR] [mixin]: Catching
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.injectCorePlugin(MixinPlatformAgentFML.java:228) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.initFMLCoreMod(MixinPlatformAgentFML.java:155) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.<init>(MixinPlatformAgentFML.java:134) [JustEnoughIDs-1.0.1-16.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_181]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:68) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:142) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:113) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:106) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:158) [JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [JustEnoughIDs-1.0.1-16.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_181]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.common.api.json requires mixin subsystem version 0.7.10
	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78) ~[JustEnoughIDs-1.0.1-16.jar:?]
	at org.spongepowered.common.launch.SpongeLaunch.setupMixinEnvironment(SpongeLaunch.java:125) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3445.jar:1.12.2-2705-7.1.0-BETA-3445]
	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:92) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3445.jar:1.12.2-2705-7.1.0-BETA-3445]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_181]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:593) ~[forge-1.12.2-14.23.4.2760-universal.jar:?]
	... 33 more
[01:59:46] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[01:59:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:59:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:59:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[01:59:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:59:48] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[01:59:48] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[01:59:48] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[01:59:48] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[01:59:48] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@30404dba
[01:59:48] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[01:59:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:59:49] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[01:59:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[01:59:49] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[01:59:49] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[01:59:50] [main/INFO] [minecraft/Minecraft]: Setting user: Demos
[01:59:54] [main/WARN] [mixin]: @Inject(@At("INVOKE")) Shift.BY=2 on mixins.jeid.core.json:MixinAnvilChunkLoader::handler$readPaletteNBT$zzd000 exceeds the maximum allowed value 0. Increase the value of maxShiftBy to suppress this warning.
[01:59:54] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[01:59:54] [main/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[01:59:56] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 191510384 bytes (182 MB) / 536870912 bytes (512 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:+UseG1GC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.93' Renderer: 'Quadro M5000M/PCIe/SSE2'
[01:59:56] [main/INFO] [FML]: MinecraftForge v14.23.4.2760 Initialized
[01:59:56] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[01:59:56] [main/INFO] [FML]: Replaced 1036 ore ingredients
[01:59:56] [main/INFO] [FML]: Searching C:\Users\barch\Documents\MultiMC\instances\stable\.minecraft\mods for mods
[01:59:58] [main/WARN] [FML]: Mod jeid is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.1-16
[01:59:58] [main/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[01:59:58] [main/WARN] [mixin]: Error loading class: biomesoplenty/common/init/ModBiomes (java.lang.ClassNotFoundException: The specified class 'biomesoplenty.common.init.ModBiomes' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: biomesoplenty/common/command/BOPCommand (java.lang.ClassNotFoundException: The specified class 'biomesoplenty.common.command.BOPCommand' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: twilightforest/block/BlockTFMagicLogSpecial (java.lang.ClassNotFoundException: The specified class 'twilightforest.block.BlockTFMagicLogSpecial' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: thaumcraft/common/lib/utils/Utils (java.lang.ClassNotFoundException: The specified class 'thaumcraft.common.lib.utils.Utils' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: com/shinoow/abyssalcraft/common/network/client/CleansingRitualMessage (java.lang.ClassNotFoundException: The specified class 'com.shinoow.abyssalcraft.common.network.client.CleansingRitualMessage' was not found)
[01:59:58] [main/WARN] [mixin]: @Mixin target com.shinoow.abyssalcraft.common.network.client.CleansingRitualMessage was not found mixins.jeid.modsupport.json:MixinCleansingRitualMessage
[01:59:58] [main/WARN] [mixin]: Error loading class: com/cutievirus/creepingnether/entity/EntityPortal (java.lang.ClassNotFoundException: The specified class 'com.cutievirus.creepingnether.entity.EntityPortal' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: climateControl/DimensionManager (java.lang.ClassNotFoundException: The specified class 'climateControl.DimensionManager' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: com/xcompwiz/mystcraft/symbol/symbols/SymbolFloatingIslands$BiomeReplacer (java.lang.ClassNotFoundException: The specified class 'com.xcompwiz.mystcraft.symbol.symbols.SymbolFloatingIslands$BiomeReplacer' was not found)
[01:59:58] [main/WARN] [mixin]: @Mixin target com.xcompwiz.mystcraft.symbol.symbols.SymbolFloatingIslands$BiomeReplacer was not found mixins.jeid.modsupport.json:MixinBiomeReplacer
[01:59:58] [main/WARN] [mixin]: Error loading class: zmaster587/advancedRocketry/util/BiomeHandler (java.lang.ClassNotFoundException: The specified class 'zmaster587.advancedRocketry.util.BiomeHandler' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: com/sk89q/worldedit/blocks/BaseBlock (java.lang.ClassNotFoundException: The specified class 'com.sk89q.worldedit.blocks.BaseBlock' was not found)
[01:59:58] [main/WARN] [mixin]: Error loading class: journeymap/client/model/ChunkMD (java.lang.ClassNotFoundException: The specified class 'journeymap.client.model.ChunkMD' was not found)
[01:59:58] [main/WARN] [mixin]: @Mixin target journeymap.client.model.ChunkMD was not found mixins.jeid.modsupport.json:MixinChunkMD
[01:59:58] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, jeid] at CLIENT
[01:59:58] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, jeid] at SERVER
[01:59:58] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 395572200 nanos
[01:59:59] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:JustEnoughIDs, ctp_1.2_MCv3.zip
[01:59:59] [main/WARN] [minecraft/AbstractResourcePack]: ResourcePack: ignored non-lowercase namespace: .DS_Store in C:\Users\barch\Documents\MultiMC\instances\stable\.minecraft\resourcepacks\ctp_1.2_MCv3.zip
[01:59:59] [main/INFO] [FML]: Processing ObjectHolder annotations
[01:59:59] [main/INFO] [FML]: Found 1169 ObjectHolder annotations
[01:59:59] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[01:59:59] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[01:59:59] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[01:59:59] [Forge Version Check/INFO] [forge.VersionCheck]: [jeid] Starting version check at https://gist.githubusercontent.com/Runemoro/67b1d8d31af58e9d35410ef60b2017c3/raw/1fe08a6c45a1f481a8a2a8c71e52d4245dcb7713/jeid_update.json
[01:59:59] [main/INFO] [FML]: Applying holder lookups
[01:59:59] [main/INFO] [FML]: Holder lookups applied
[01:59:59] [main/INFO] [FML]: Applying holder lookups
[01:59:59] [main/INFO] [FML]: Holder lookups applied
[01:59:59] [main/INFO] [FML]: Applying holder lookups
[01:59:59] [main/INFO] [FML]: Holder lookups applied
[01:59:59] [main/INFO] [FML]: Applying holder lookups
[01:59:59] [main/INFO] [FML]: Holder lookups applied
[01:59:59] [main/INFO] [FML]: Injecting itemstacks
[01:59:59] [main/INFO] [FML]: Itemstack injection complete
[02:00:00] [Forge Version Check/INFO] [forge.VersionCheck]: [jeid] Found status: AHEAD Target: null
[02:00:00] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[02:00:00] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: AHEAD Target: null
[02:00:00] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[02:00:01] [Thread-5/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[02:00:01] [Thread-5/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[02:00:01] [Thread-5/INFO] [minecraft/SoundManager]: OpenAL initialized.
[02:00:01] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[02:00:04] [main/INFO] [FML]: Max texture size: 16384
[02:00:08] [main/INFO] [minecraft/TextureMap]: Created: 512x512 textures-atlas
[02:00:08] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_flat
[02:00:08] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_flat
[02:00:08] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_raised_sw
[02:00:08] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_raised_ne
[02:00:08] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_raised_sw
[02:00:09] [main/WARN] [minecraft/ModelBlock]: Unable to resolve texture due to upward reference: #rail in minecraft:models/block/golden_rail_raised_ne
[02:00:09] [main/INFO] [FML]: Applying holder lookups
[02:00:09] [main/INFO] [FML]: Holder lookups applied
[02:00:09] [main/INFO] [FML]: Injecting itemstacks
[02:00:09] [main/INFO] [FML]: Itemstack injection complete
[02:00:09] [main/WARN] [FML]: No types have been added to Biome jeid:error_biome, types have been assigned on a best-effort guess: [PLAINS]
[02:00:10] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[02:00:10] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[02:00:10] [main/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[02:00:28] [main/INFO] [minecraft/Minecraft]: Stopping!
[02:00:28] [main/INFO] [minecraft/SoundManager]: SoundSystem shutting down...
[02:00:28] [main/WARN] [minecraft/SoundManager]: Author: Paul Lamb, www.paulscode.com
Process exited with code 0.
Clipboard copy at: 16 Sep 2018 02:00:30 -0400
```

This may be unavoidable since sponge needs to hook into quite a bit

**Comment by ben-mkiv** [comment]
try to rename your sponge mod to something like aaSponge.jar so its loaded before JEID

**Comment by Rongmario** [comment]
Don't think so as FML doesn't determine mixins loading order.

**Comment by 0-x-2-2** [comment]
Its the core-mod loading order

**Comment by TacticalUniverse** [comment]
All I did was changed the sponge jar to A.jar to have it load before all the mods and have not had an issue with Sponge and JustEnoughIDs.

**Comment by Muzixs** [comment]
I've been trying to run a StoneBlock modpack server with Sponge which uses this mod and I get an error similar to the one mentioned on this thread. I get all the way to the world gen when the [following crash](https://pastebin.com/c6Tqy76j) occurs. I've [inquired about the matter](https://github.com/Sunekaer/stoneBlock/issues/461) with the dev of the pack in hopes of an answer. I now seek further assistance on the matter with the author of the mod in question.

**Comment by fewizz** [comment]
have you tried suggested fix?
