### ISSUE TITLE
Incompatibility with Weather2 or Climate Control?

### ISSUE THREAD

**Issue by idiocracy1984** [DimensionalDevelopment/JustEnoughIDs#34]
Since I have instaled this mod I have had this error thrown at me that I have never encountered before. It is an issue with Biome IDs. Is there a way to fix this or is it an issue with the mod or..?  :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.4.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  FCFMLCorePlugin (FinderCompass-1.12.1.jar)
  RandomPatches (randompatches-1.12.2-1.4.1.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-84-core.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ShetiPhian-ASM (shetiphian-asm.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/16/18 8:39 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.RuntimeException: biome ID230200 climateControl.customGenLayer.GenLayerLock@7ac3b84c
	at climateControl.customGenLayer.GenLayerLowlandRiverMix.func_75904_a(GenLayerLowlandRiverMix.java:66)
	at climateControl.customGenLayer.GenLayerRiverMixWrapper.func_75904_a(GenLayerRiverMixWrapper.java:95)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:22)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:128)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:65)
	at net.minecraft.world.World.getBiomeForCoordsBody(World.java:177)
	at net.minecraft.world.WorldProvider.getBiomeForCoords(WorldProvider.java:429)
	at net.minecraft.world.World.func_180494_b(World.java:148)
	at weather2.weathersystem.storm.StormObject.tickProgression(StormObject.java:1101)
	at weather2.weathersystem.storm.StormObject.tick(StormObject.java:606)
	at weather2.weathersystem.WeatherManagerBase.tick(WeatherManagerBase.java:138)
	at weather2.weathersystem.WeatherManagerServer.tick(WeatherManagerServer.java:52)
	at weather2.ServerTickHandler.onTickInGame(ServerTickHandler.java:92)
	at weather2.EventHandlerFML.tickServer(EventHandlerFML.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_998_EventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: biome ID230200 climateControl.customGenLayer.GenLayerLock@7ac3b84c
	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:44)
	at climateControl.genLayerPack.GenLayerAddIsland.func_75904_a(GenLayerAddIsland.java:26)
	at climateControl.customGenLayer.GenLayerSmoothCoast.func_75904_a(GenLayerSmoothCoast.java:43)
	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
	at climateControl.customGenLayer.GenLayerSmoothCoast.func_75904_a(GenLayerSmoothCoast.java:43)
	at climateControl.customGenLayer.GenLayerPrettyShore.func_75904_a(GenLayerPrettyShore.java:43)
	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
	at climateControl.genLayerPack.GenLayerSmooth.func_75904_a(GenLayerSmooth.java:32)
	at climateControl.customGenLayer.GenLayerLowlandRiverMix.func_75904_a(GenLayerLowlandRiverMix.java:63)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4325679824 bytes (4125 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 35, tcache: 110, allocated: 1, tallocated: 8
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D3 114 mods loaded, 114 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                      | Source                                         | Signature                                |
	|:--------- |:----------------------- |:---------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                       | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                         | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                    | modpack.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.3.2655                 | modpack.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit               | 1.3.3-1.12                   | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | obfuscate               | 0.2.5                        | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | srm-hooks               | 1.12.2-1.0.0                 | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | randompatches           | 1.12.2-1.4.1.1               | randompatches-1.12.2-1.4.1.1.jar               | None                                     |
	| UCHIJAAAA | appliedenergistics2     | rv6-alpha-2                  | appliedenergistics2-rv6-alpha-2.jar            | None                                     |
	| UCHIJAAAA | bdlib                   | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                   | None                                     |
	| UCHIJAAAA | ae2stuff                | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                  | None                                     |
	| UCHIJAAAA | ambience                | GRADLE:VERSION-GRADLE:BUILD  | Ambience+1.1-10.jar                            | None                                     |
	| UCHIJAAAA | architecturecraft       | @VERSION@                    | architecturecraft-1.12-2.68.jar                | None                                     |
	| UCHIJAAAA | quark                   | r1.4-125                     | Quark-r1.4-125.jar                             | None                                     |
	| UCHIJAAAA | autoreglib              | 1.3-18                       | AutoRegLib-1.3-18.jar                          | None                                     |
	| UCHIJAAAA | betterfoliage           | 2.1.10                       | BetterFoliage-MC1.12-2.1.10.jar                | None                                     |
	| UCHIJAAAA | betterquesting          | 3.5.262                      | BetterQuesting-3.5.262.jar                     | None                                     |
	| UCHIJAAAA | betterunderground       | 1.1.2                        | betterunderground-1.1.2.jar                    | None                                     |
	| UCHIJAAAA | bibliocraft             | 2.4.5                        | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| UCHIJAAAA | biomesoplenty           | 7.0.1.2399                   | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar  | None                                     |
	| UCHIJAAAA | bookshelf               | 2.3.553                      | Bookshelf-1.12.2-2.3.553.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | buildcraftlib           | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftcore          | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftbuilders      | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftenergy        | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftfactory       | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftrobotics      | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcrafttransport     | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftsilicon       | 7.99.17                      | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftcompat        | 7.99.14                      | buildcraft-compat-7.99.14.jar                  | None                                     |
	| UCHIJAAAA | ceramics                | 1.12-1.3.4                   | Ceramics-1.12-1.3.4.jar                        | None                                     |
	| UCHIJAAAA | cfm                     | 5.4.1                        | cfm-5.4.1-mc1.12.2.jar                         | None                                     |
	| UCHIJAAAA | ctm                     | MC1.12.2-0.3.1.16            | CTM-MC1.12.2-0.3.1.16.jar                      | None                                     |
	| UCHIJAAAA | chisel                  | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                   | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.2.0.345                    | CodeChickenLib-1.12.2-3.2.0.345-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | compactmachines3        | 3.0.12                       | compactmachines3-1.12.2-3.0.12-b215.jar        | None                                     |
	| UCHIJAAAA | coralreef               | 2.0                          | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | extendedrenderer        | v1.0                         | coroutil-1.12.1-1.2.13.jar                     | None                                     |
	| UCHIJAAAA | coroutil                | 1.12.1-1.2.13                | coroutil-1.12.1-1.2.13.jar                     | None                                     |
	| UCHIJAAAA | configmod               | v1.0                         | coroutil-1.12.1-1.2.13.jar                     | None                                     |
	| UCHIJAAAA | custommainmenu          | 2.0.8                        | CustomMainMenu-MC1.12.2-2.0.8.jar              | None                                     |
	| UCHIJAAAA | ptrmodellib             | 1.0.2                        | PTRLib-1.0.2.jar                               | None                                     |
	| UCHIJAAAA | props                   | 2.6.0                        | Decocraft-2.6.0_1.12.2.jar                     | None                                     |
	| UCHIJAAAA | cdm                     | 0.4.1                        | device-mod-0.4.1-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | elevatorid              | 1.3.6                        | ElevatorMod-1.12.2-1.3.6.jar                   | None                                     |
	| UCHIJAAAA | enderstorage            | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extraalchemy            | 0.3.8.5-release              | extraalchemy-0.3.8.5-release.jar               | None                                     |
	| UCHIJAAAA | extracells              | 2.5.13                       | ExtraCells-1.12.2-2.5.13a60.jar                | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                          | extrautils2-1.12-1.8.5.jar                     | None                                     |
	| UCHIJAAAA | fastleafdecay           | v14                          | FastLeafDecay-v14.jar                          | None                                     |
	| UCHIJAAAA | fcl                     | XII.42                       | Fexcraft+Common+Library-XII.42.jar             | None                                     |
	| UCHIJAAAA | findercompass           | 1.12                         | FinderCompass-1.12.1.jar                       | None                                     |
	| UCHIJAAAA | forgelin                | 1.7.4                        | Forgelin-1.7.4.jar                             | None                                     |
	| UCHIJAAAA | fvtm                    | 2.7.31                       | FVTM-2.7.31-1.12.x.jar                         | None                                     |
	| UCHIJAAAA | geographicraft          | 0.8.7                        | GeographiCraft-1.12-0.8.9b.jar                 | None                                     |
	| UCHIJAAAA | guideapi                | 1.12-2.1.7-62                | Guide-API-1.12-2.1.7-62.jar                    | None                                     |
	| UCHIJAAAA | cgm                     | 0.4.3                        | guns-0.4.3-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | jei                     | 4.11.0.206                   | jei_1.12.2-4.11.0.206.jar                      | None                                     |
	| UCHIJAAAA | immersiveengineering    | 0.12-84                      | ImmersiveEngineering-0.12-84.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivecables         | 1.3.1                        | ImmersiveCables-1.12.2-1.3.1.jar               | None                                     |
	| UCHIJAAAA | trackapi                | 1.1                          | TrackAPI-1.1_1.12.jar                          | None                                     |
	| UCHIJAAAA | immersiverailroading    | 1.3.2                        | ImmersiveRailroading-1.3.2_1.12.jar            | None                                     |
	| UCHIJAAAA | ic2                     | 2.8.97-ex112                 | industrialcraft-2-2.8.97-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | mekanism                | 1.12.2-9.4.13.349            | Mekanism-1.12.2-9.4.13.349.jar                 | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.15                       | tesla-core-lib-1.12.2-1.0.15.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2                | industrialforegoing-1.12.2-1.10.3-181.jar      | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                       | None                                     |
	| UCHIJAAAA | natura                  | 1.12.2-4.3.2.49              | natura-1.12.2-4.3.2.49.jar                     | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.2u                      | Pam's+HarvestCraft+1.12.2u.jar                 | None                                     |
	| UCHIJAAAA | silentlib               | 2.3.0                        | SilentLib-1.12.2-2.3.0-106.jar                 | None                                     |
	| UCHIJAAAA | silentgems              | 2.7.0                        | SilentsGems-1.12-2.7.0-266.jar                 | None                                     |
	| UCHIJAAAA | integrationforegoing    | 1.12.2-1.7.2                 | IntegrationForegoing-1.12.2-1.7.2.jar          | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAAAA | inventorytweaks         | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks           | 1.12.2-3.0.8-12              | IronBackpacks-1.12.2-3.0.8-12.jar              | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.44.829            | ironchest-1.12.2-7.0.44.829.jar                | None                                     |
	| UCHIJAAAA | irontanks               | 2.1.0-beta.5                 | irontanks-2.1.0-beta.5.jar                     | None                                     |
	| UCHIJAAAA | journeymap              | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                    | None                                     |
	| UCHIJAAAA | jeid                    | 1.0.1-16                     | JustEnoughIDs-1.0.1-16.jar                     | None                                     |
	| UCHIJAAAA | levelup2                | ${version}                   | Level+Up!+2-1.1.22-1.12.jar                    | None                                     |
	| UCHIJAAAA | malisiscore             | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                   | None                                     |
	| UCHIJAAAA | malisisdoors            | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| UCHIJAAAA | mekanismgenerators      | 9.4.11                       | MekanismGenerators-1.12.2-9.4.13.349.jar       | None                                     |
	| UCHIJAAAA | mineralogy              | 3.4.0                        | Mineralogy-1.12-3.4.0.29.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | morpheus                | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                        | None                                     |
	| UCHIJAAAA | mousetweaks             | 2.8                          | MouseTweaks-2.8-mc1.12.1.jar                   | None                                     |
	| UCHIJAAAA | recipehandler           | 0.11                         | NoMoreRecipeConflict-0.11(1.12.2).jar          | None                                     |
	| UCHIJAAAA | neid                    | 1.5.4.2                      | NotEnoughIDs-1.5.4.2.jar                       | None                                     |
	| UCHIJAAAA | nutrition               | 3.5.0                        | Nutrition-1.12.2-3.5.0.jar                     | None                                     |
	| UCHIJAAAA | samsocean               | 1.0.1                        | OceanFloor-1.12-1.0.1.jar                      | None                                     |
	| UCHIJAAAA | packingtape             | 0.7.6                        | PackingTape-1.12.2-0.7.6.jar                   | None                                     |
	| UCHIJAAAA | clayspawn               | 1.12a                        | Pam's+ClaySpawn+1.12a.jar                      | None                                     |
	| UCHIJAAAA | simplerecipes           | 1.12.2c                      | Pam's+Simple+Recipes+1.12.2c.jar               | None                                     |
	| UCHIJAAAA | pixelmon                | 2.2.0                        | PixelmonGenerations-1.12.2-2.2.1-universal.jar | None                                     |
	| UCHIJAAAA | pixelextras             | 2.3.8                        | PixelExtras-1.12.2-2.3.8-universal.jar         | None                                     |
	| UCHIJAAAA | placeableitems          | 3.3                          | placeableitems-3.3.jar                         | None                                     |
	| UCHIJAAAA | placebo                 | 1.4.0                        | Placebo-1.12.2-1.4.0.jar                       | None                                     |
	| UCHIJAAAA | plants2                 | 2.9.2                        | Plants-1.12.2-2.9.2.jar                        | None                                     |
	| UCHIJAAAA | poweradapters           | 1.0.9                        | PowerAdapters-1.12.2-1.0.9.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | realworld               | 1.16                         | realworld-1.16.jar                             | None                                     |
	| UCHIJAAAA | reccomplex              | 1.4.7                        | RecurrentComplex-1.4.7.jar                     | None                                     |
	| UCHIJAAAA | ropebridge              | 2.0.5                        | ropebridge-1.12-2.0.7.jar                      | None                                     |
	| UCHIJAAAA | secretroomsmod          | 5.6.4                        | secretroomsmod-1.12.2-5.6.4.jar                | None                                     |
	| UCHIJAAAA | sereneseasons           | 1.2.6                        | SereneSeasons-1.12.2-1.2.6-universal.jar       | None                                     |
	| UCHIJAAAA | shetiphiancore          | 3.5.7                        | shetiphiancore-1.12.0-3.5.7.jar                | None                                     |
	| UCHIJAAAA | somanyenchantments      | 0.3.0                        | SoManyEnchantments+V0.3.1+(1.12.2).jar         | None                                     |
	| UCHIJAAAA | tellme                  | 0.6.0-dev.20180416.050059    | tellme-1.12.2-0.6.0-dev.20180416.050059.jar    | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | terraqueous             | 1.4.12                       | terraqueous-1.12.0-1.4.12.jar                  | None                                     |
	| UCHIJAAAA | toughasnails            | 3.1.0.128                    | ToughAsNails-1.12.2-3.1.0.128-universal.jar    | None                                     |
	| UCHIJAAAA | tumbleweed              | 1.11-0.4.5                   | tumbleweed-1.11-0.4.5.jar                      | None                                     |
	| UCHIJAAAA | waterstrainer           | 3.2.0                        | WaterStrainer-1.12-3.2.0.jar                   | None                                     |
	| UCHIJAAAA | waystones               | 4.0.54                       | Waystones_1.12.2-4.0.54.jar                    | None                                     |
	| UCHIJAAAA | weather2                | 1.12.1-2.6.12                | weather2-1.12.1-2.6.12.jar                     | None                                     |
	| UCHIJAAAA | wondertrade             | 4.5.1                        | WonderTrade-1.12.2-4.5.3-universal.jar         | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.15                       | tesla-core-lib-1.12.2-1.0.15.jar               | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.7.4.jar)
  
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.1.16.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
FCFMLCorePlugin (FinderCompass-1.12.1.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
RandomPatches (randompatches-1.12.2-1.4.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-84-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
ShetiPhian-ASM (shetiphian-asm.jar)
  shetiphian.asm.ClassTransformer
JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv6-alpha-2 for Forge 14.23.3.2655
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-alpha-2.jar
		* BetterQuesting|API (3.1) from BetterQuesting-3.5.262.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.262.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.4-125.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.17.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.17.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.12.1-1.2.13.jar
		* CSLib|API (1.0.1) from PTRLib-1.0.2.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.1.16.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.7-62.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-84.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-84.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.10.3-181.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.206.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* QuarkAPI (2) from Quark-r1.4-125.jar
		* SilentGemsAPI (4) from SilentsGems-1.12-2.7.0-266.jar
		* TerraqueousAPI (1.0) from terraqueous-1.12.0-1.4.12.jar
		* TerraqueousAPI|Cloud (1.0) from terraqueous-1.12.0-1.4.12.jar
		* TerraqueousAPI|Machines (1.0) from terraqueous-1.12.0-1.4.12.jar
		* TerraqueousAPI|Plant (1.0) from terraqueous-1.12.0-1.4.12.jar
	
	FVTM Addons: 
	| generic | General Essentials Pack | 1.6.1 | ...Essentials Pack-1.6.1-1.12.x.jar|
	| hcp     | Heavy Cargo Pack        | 1.4.1 | ...eavy Cargo Pack-1.4.1-1.12.x.jar|

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Aevumdefluo'/1933, l='Development', x=250.81, y=104.70, z=236.37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by aevumdefluo** [comment]
Same Here. Weird.
