### ISSUE TITLE
Crash with lattest JustEnoughIDs-1.0.2-25.jar

### ISSUE THREAD

**Issue by VladimirMangos** [DimensionalDevelopment/JustEnoughIDs#39]
MC load fine with build 24 but crash with 5 with error
```
[00:12:35] [main/FATAL]: Mixin prepare failed preparing client.MixinMinecraft in mixins.vanillafix.bugs.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[JustEnoughIDs-1.0.2-25.jar:?]

```

Full log https://paste2.org/XHfJnEbd

**Comment by TacticalUniverse** [comment]
I just got this same error and does not make any sense as Sponge is not a client-side mod but used only on servers.

**Comment by ZombieHDGaming** [comment]
Apparently someone is patching the main Minecraft class before us. Do you have any idea which mod is logging this: `Patching net.minecraft.client.Minecraft`?

**Comment by ZombieHDGaming** [comment]
If I can get a mod list or link to said pack, I can look further into it. But as of this moment, it's a mod compat issue between VanillaFix and another mod.

**Comment by TacticalUniverse** [comment]
[17:46:32] [main/INFO] [Aroma1997Core]: Finished data injection.
[17:46:32] [main/INFO] [Aroma1997Core]: Finished data injection.
[17:46:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:33] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[17:46:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[17:46:34] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[17:46:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:34] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[17:46:34] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[17:46:34] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[17:46:34] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@17b6ad97
[17:46:34] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[17:46:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:46:34] [main/INFO] [FML]: [AstralTransformer] Loading patches...
[17:46:35] [main/INFO] [FML]: [AstralTransformer] Found 0 Transformers! Trying to recover with direct references...
[17:46:35] [main/INFO] [FML]: [AstralTransformer] Initialized! Loaded 8 class patches!
[17:46:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:39] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:46:39] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:46:39] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[17:46:40] [main/INFO] [BetterFps]: Patching net.minecraft.block.Block... (aow)
[17:46:40] [main/INFO] [mixin]: A re-entrant transformer 'guichaguri.betterfps.transformers.PatcherTransformer' was detected and will no longer process meta class data
[17:46:41] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.lumien.randomthings.asm.ClassTransformer' was detected and will no longer process meta class data
[17:46:41] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[17:46:41] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.block.Block Finished.
[17:46:41] [main/INFO] [FML]: [AstralTransformer] Transforming axw : net.minecraft.world.chunk.Chunk with 1 patches!
[17:46:41] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHBLOCKMODIFY
[17:46:41] [main/INFO] [STDOUT]: [pl.asie.patchy.helpers.ConstructorReplacingTransformer$FFMethodVisitor:visitTypeInsn:75]: Replaced NEW for net/minecraft/util/ClassInheritanceMultiMap to pl/asie/foamfix/coremod/common/FoamyClassInheritanceMultiMap
[17:46:41] [main/INFO] [STDOUT]: [pl.asie.patchy.helpers.ConstructorReplacingTransformer$FFMethodVisitor:visitMethodInsn:87]: Replaced INVOKESPECIAL for net/minecraft/util/ClassInheritanceMultiMap to pl/asie/foamfix/coremod/common/FoamyClassInheritanceMultiMap
[17:46:41] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.pl.asie.foamfix.coremod.FoamFixTransformer' was detected and will no longer process meta class data
[17:46:42] [main/INFO] [FML]: [AstralTransformer] Transforming alm : net.minecraft.enchantment.EnchantmentHelper with 1 patches!
[17:46:42] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHMODIFYENCHANTMENTLEVELS
[17:46:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinClientNotif$MixinWorld, name: net.malisis.core.asm.mixin.core.MixinClientNotif$MixinWorld
[17:46:42] [main/INFO] [FML]: [AstralTransformer] Transforming amu : net.minecraft.world.World with 2 patches!
[17:46:42] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCLIENT
[17:46:42] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCOMMON
[17:46:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinClientNotif$MixinWorldServer, name: net.malisis.core.asm.mixin.core.MixinClientNotif$MixinWorldServer
[17:46:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinChunk, name: net.malisis.core.asm.mixin.core.MixinChunk
[17:46:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinChunkCollision$MixinItemBlock, name: net.malisis.core.asm.mixin.core.MixinChunkCollision$MixinItemBlock
[17:46:42] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinChunkCollision$MixinNetHandlerPlayServer, name: net.malisis.core.asm.mixin.core.MixinChunkCollision$MixinNetHandlerPlayServer
[17:46:42] [main/INFO] [BetterFps]: Patching net.minecraft.client.Minecraft... (bib)
[17:46:43] [main/INFO] [FML]: [AstralTransformer] Transforming aip : net.minecraft.item.ItemStack with 2 patches!
[17:46:43] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHMODIFYENCHANTMENTLEVELSTOOLTIP
[17:46:43] [main/INFO] [FML]: [AstralTransformer] Applied patch PATCHMODIFYENCHANTMENTLEVELSTOOLTIPEVENT
[17:46:43] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.therandomlabs.randompatches.core.RPTransformer' was detected and will no longer process meta class data
[17:46:43] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:MixinChunkCollision$MixinWorld, name: net.malisis.core.asm.mixin.core.MixinChunkCollision$MixinWorld
[17:46:43] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:client.MixinTextureMap, name: net.malisis.core.asm.mixin.core.client.MixinTextureMap
[17:46:43] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.client.renderer.texture.TextureMap], Method [registerSprite]
[17:46:43] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.client.renderer.texture.TextureMap Finished.
[17:46:43] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:client.MixinMalisisRenderer$MixinBlockRendererDispatcher, name: net.malisis.core.asm.mixin.core.client.MixinMalisisRenderer$MixinBlockRendererDispatcher
[17:46:43] [main/INFO] [LibrarianLib ASM]: Transforming BlockRendererDispatcher
[17:46:43] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [renderBlock, func_175018_a] Descriptor (Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/client/renderer/BufferBuilder;)Z)
[17:46:43] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Block render hook
[17:46:43] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[17:46:43] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [renderBlock, func_175018_a] Descriptor (Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/client/renderer/BufferBuilder;)Z)
[17:46:43] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Fluid render hook
[17:46:43] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[17:46:43] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:client.MixinMalisisRenderer$MixinRenderItem, name: net.malisis.core.asm.mixin.core.client.MixinMalisisRenderer$MixinRenderItem
[17:46:43] [main/INFO] [LibrarianLib ASM]: Transforming RenderItem
[17:46:43] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [renderItem, func_180454_a] Descriptor (Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/block/model/IBakedModel;)V)
[17:46:43] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Item render hook
[17:46:43] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[17:46:43] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [renderEffect, func_191966_a] Descriptor (Lnet/minecraft/client/renderer/block/model/IBakedModel;)V)
[17:46:43] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Enchantment glint glow activation
[17:46:43] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[17:46:43] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [renderEffect, func_191966_a] Descriptor (Lnet/minecraft/client/renderer/block/model/IBakedModel;)V)
[17:46:43] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Enchantment glint glow return
[17:46:43] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[17:46:43] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.teamwizardry.librarianlib.asm.LibLibTransformer' was detected and will no longer process meta class data
[17:46:43] [main/INFO] [STDOUT]: [elucent.elulib.asm.ASMTransformer:patchRenderItemASM:124]: Successfully loaded RenderItem ASM!
[17:46:44] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.client.renderer.RenderItem], Method [func_180453_a, func_184391_a]
[17:46:44] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.client.renderer.RenderItem Finished.
[17:46:44] [main/ERROR] [mixin]: Classloader restrictions [PACKAGE_TRANSFORMER_EXCLUSION] encountered loading mixins.malisiscore.core.json:client.MixinMalisisRenderer$MixinBlockModelShapes, name: net.malisis.core.asm.mixin.core.client.MixinMalisisRenderer$MixinBlockModelShapes
[17:46:44] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:28]: [wizardry ASM] Successfully patched -> 'func_70091_d', 'move' with '(Lnet/minecraft/entity/MoverType;DDD)V'
[17:46:44] [main/FATAL] [mixin]: Mixin prepare failed preparing client.MixinMinecraft in mixins.vanillafix.bugs.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:46:44] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.vanillafix.bugs.json:client.MixinMinecraft] from phase [DEFAULT] in config [mixins.vanillafix.bugs.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.bugs.json:client.MixinMinecraft target net.minecraft.client.Minecraft was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[JustEnoughIDs-1.0.2-25.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:46:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TacticalUniverse** [comment]
see if that helps @ZombieHDGaming

**Comment by ZombieHDGaming** [comment]
@VladimirMangos and @TacticalUniverse either remove RandomPatches or rename the VanillaFix jar file to something like aaaaVanilaFix-1.0.9-97.jar to fix the coremod loading issue. Apparently they do not like each other very much.

**Comment by TheRandomLabs** [comment]
@ZombieHDGaming Is there any reason you are loading `net.minecraft.client.Minecraft` [here](https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/b1ea665235b9d5a53bea21c76a5549fb8c3f0559/src/main/java/org/dimdev/jeid/JEIDTransformer.java#L129)? It is causing the class to be transformed too early by RandomPatches. As far as I know, you can call `FMLLaunchHandler.side().isClient()` instead to ensure the code is being called client-side.

**Comment by ZombieHDGaming** [comment]
@TheRandomLabs Tested and that seemed to be proper. Not sure why that would cause RandomPatches to transform it too early though, but it fixes it so whatever. I'll push a new release to CurseForge to fix it.

**Comment by TheRandomLabs** [comment]
Class.forName causes the class to be loaded, which triggers the transformer.
