### ISSUE TITLE
bug of WorldEdit 

### ISSUE THREAD

**Issue by HuaXiY** [DimensionalDevelopment/JustEnoughIDs#66]
[19:24:59] [Server thread/INFO]: Huaxi issued server command: //copy
[19:24:59] [Server thread/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[ParametricCallable.class:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[SimpleDispatcher.class:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:249) [CommandManager.class:?]
at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [MethodEventHandler.class:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [EventHandler.class:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [EventBus.class:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [EventBus.class:?]
at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:145) [ForgeWorldEdit.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_451_ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) [EventBus.class:?]
at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:62) [bj.class:?]
at catserver.server.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51) [CraftSimpleCommandMap.class:git-4749966-Community]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:715) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1591) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1436) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:845) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:782) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Can't have a block ID above 4095 (4531 given)
at com.sk89q.worldedit.blocks.BaseBlock.internalSetId(BaseBlock.java:145) ~[BaseBlock.class:?]
at com.sk89q.worldedit.blocks.BaseBlock.<init>(BaseBlock.java:102) ~[BaseBlock.class:?]
at com.sk89q.worldedit.forge.ForgeWorld.getBlock(ForgeWorld.java:360) ~[ForgeWorld.class:?]
at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:417) ~[EditSession.class:?]
at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:71) ~[ExtentBlockCopy.class:?]
at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[RegionMaskingFilter.class:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57) ~[RegionVisitor.class:?]
at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[DelegateOperation.class:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[Operations.class:?]
at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:91) ~[ClipboardCommands.class:?]
... 35 more

 Click to attach, drag files, or press Ctrl+V to paste an image
Activity settings
 
Matthew Miller  commented 17 minutes ago
 Not a WorldEdit issue, you're using a mod that's added blocks that are above Minecraft's limit. Mods like NotEnoughIDs patch WorldEdit to allow it.
 
Huaxi  commented just now
@Matthew Miller i use JustEnoughIDs，because NotEnoughIDs in my server will be crash。
Can you just JustEnoughIDs to patch WorldEdit？

 
Matthew Miller  commented just now
 That's up to them, not us. You'd have to report it to them.

**Comment by HuaXiY** [comment]
add block exceed 4096 。WorldEdit out of commission。
but Author say NotEnoughIDs can repair
I hope JustEnoughIDs patch WorldEdit

**Comment by wizjany** [comment]
Just had a user report that this is likely caused by LiteLoader.
For whatever reason, having liteloader installed causes the WE mixin (https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/modsupport/worldedit/MixinBaseBlock.java) not to apply.

**Comment by HuaXiY** [comment]
> 刚刚有一个用户报告，这很可能是由LiteLoader引起的。
> 无论出于何种原因，安装liteloader会导致WE mixin（https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/modsupport/worldedit/MixinBaseBlock.java）不申请。（可能是由于混合的恶作剧。虽然idk，只是说我听到的，如果它有帮助）

But my server no install LiteLoader
