### ISSUE TITLE
All blocks invisible on vanilla server

### ISSUE THREAD

**Issue by Magi1053** [DimensionalDevelopment/JustEnoughIDs#70]
I am connecting to a 1.12 server running Paper and the ViaVersion plugin. When I log into the server, I am greeted with every single block being invisible
![java_QPGJ5bda0n](https://user-images.githubusercontent.com/1045179/60224843-d7ad3c80-9849-11e9-9f40-98a684eb7a73.png)

When I look at my client's console, I am receiving this error message:
```[19:32:57] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at net.minecraft.world.chunk.Chunk.setIntBiomeArray(Chunk.java:1649) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.redirect$readBiomeByteArray$zzi000(Chunk.java:2131) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1182) ~[axw.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

**Comment by ZombieHDGaming** [comment]
Just gonna say no. Cause you have no reason to connect to a VANILLA server with JEID installed, so there is no need for this issue to be open.

**Comment by Magi1053** [comment]
Uh, yes there is. Have you ever heard of a portal hub server?

**Comment by ZombieHDGaming** [comment]
Well, all I can assume is that this is an incompatibility with ViaVersion, as we have people on networks use the mod and have minimal to no issues. Since ViaVersion works by sending custom packets, I can only assume that it is sending packets that are being misinterpreted by the client leading to that. If you are able to reproduce this without ViaVersion (or just a normal network in general), then I'd have a better idea of where to look to fix this.

Plus, I'd need additional info to debug the situation. By with what you've given, I'm gonna guess ViaVersion, but I am unsure.

**Comment by Magi1053** [comment]
Now I have tried the lobby world with no plugins installed, and I even tried using Spigot instead of Paper, and I am still encountering this issue.

**Comment by Magi1053** [comment]
Perhaps it is worth also noting that I am using Velocity as my Proxy with the BungeeCord protocol

**Comment by Magi1053** [comment]
The issue seems to be coming from the world save itself. If I load up everything normally but with a fresh world then it works fine.

**Comment by Magi1053** [comment]
Please observe this clip I recorded showing what is happening 
(I made a new world and pasted a schematic)
https://dl3.pushbulletusercontent.com/9Mdj18qtImgLpm05iWFNCPYy4rgK24Ql/roiYjOor1Y.mp4

**Comment by Magi1053** [comment]
@ZombieHDGaming Is there any more information I can provide to help you diagnose this issue?

**Comment by Magi1053** [comment]
@ZombieHDGaming I am still having this issue, please respond if there is anything else I can help assist you with solving this issue.

**Comment by Sir-Will** [comment]
@Magi1053 did you find a solution?

**Comment by Magi1053** [comment]
@Sir-Will nope I uninstalled the mod and started a new world

**Comment by Runemoro** [comment]
Like many other mods, JEID is not a client-only mod, so you'll need to install it on the server too.

**Comment by Sir-Will** [comment]
Which the server with all the other mods has but this is the only mod which causes major issues like this if you are joining a vanilla server.

**Comment by Runemoro** [comment]
Almost no mods support joining a server that doesn't have the mod installed. Whether it will work, crash when you interact with some UI, crash when you join, or produce strange behavior depends on your luck.

If you make a PR that adds support for joining vanilla servers, and the PR doesn't complicate the rest of the mod's code too much, then it might get accepted. Otherwise, this is too low priority for me to work on, as joining vanilla servers with mods installed is not something that's supported by nearly anyone.

**Comment by Sunconure11** [comment]
Speaking of PRs, and I hate to hijack this, but did you ever figure out why I was unable to compile a workspace with this mod? I wanted to try and send a fix over for my own mod, but could not do so, due to the workspace refusing to build. I'm aware you sent the idea of the fix over to Zombie, but I'm curious anyways.
